### PR TITLE
Switch to CoreOS

### PR DESCRIPTION
**Pull request by khuedoan**
Benefits:

- Automatic update
- Atomic upgrade
- Immutable
- Minimal
- Faster install time (3 minutes compare to 5 minutes on Fedora or CentOS)
- Faster provisioning (Docker already installed, save 5 minutes)

### CODE REVIEW

**Review by locmai — APPROVED** [review]
LGTM

**Comment by locmai** [comment]
thinking about putting the GH action for linting?

**Comment by khuedoan** [comment]
> thinking about putting the GH action for linting?

I'm thinking Tekton :wink:

**Comment by locmai** [comment]
way too many components needed for just a job runner.

**Pull request merged**
