### PR TITLE
fix(argocd)!: use Server-Side Diff

### LINKED ISSUE #105: Random OutOfSync with ArgoCD server-side apply
If you see applications getting out of sync due to some random diff like this:

image

This is a known issue, see `https://github.com/argoproj/argo-cd/issues/11143`

### PR DESCRIPTION
**Pull request by retX0**
The issue has been close and fixed, see [commit](https://github.com/Japan7/nanak8s/commit/23766041fa2feb096b6f5bad23bebe4a189c40d6#diff-ffd30a9c025f2a78bb35f6f6e3187cc906ebac42eef6080d24bd3c796a827233)

### CODE REVIEW

**Comment by khuedoan** [comment]
Thank you, I just merged the ArgoCD upgrade to v6 so this is now available, I think it's better to enable it globally under `bootstrap/argocd/values.yaml`, since we'll need in in all Applications anyway:

```yaml
argo-cd:
  configs:
    cm:
      # ...
    params:
      controller.diff.server.side: true
```

Ref: https://argo-cd.readthedocs.io/en/stable/user-guide/diff-strategies/#enabling-it

**Comment by khuedoan** [comment]
I also changed the title to indicate that this is a breaking change (switching from client side to server side may recreate some resources - at least in my setup)

**Comment by retX0** [comment]
I pull my code and changed the code.

**Review by khuedoan — APPROVED** [review]
Thank you!

**Pull request merged**
